# Emory K. Dev Python Tutorial

## Set-Up
* [Anaconda](https://www.continuum.io/downloads) (Python 3.6.0)
* [Git](https://git-scm.com/downloads)
* [PyCharm](https://www.jetbrains.com/pycharm/) (Preferred Python IDE) ::: consider Spyder (part of Anaconda) for scientific computing

## Ch 1 : Hello World

In [1]:
# Compare this to Java Hello World
print("Hello World!")

Hello World!


In [2]:
# Single-line Comment
# Fundamentally, python is a scripting language suited for high-level programming with remarkable clarity and simplicity.

'''
Block Comment : This is another way to comment out multiple of lines!
Seems like the convention is to use this to provide descriptions for methods.
I will explain this a bit later, but for now just be aware of the shortcut:
(Windows) C + /
(Mac) cmd + / 
-> Write a couple of random lines below this block comment, grab them and try the shortcut!
'''

# this is an example!
# I am writing random stuff here,
# and ther... and now
# I click cmd + / !!!

'\nBlock Comment : This is another way to comment out multiple of lines!\nSeems like the convention is to use this to provide descriptions for methods.\nI will explain this a bit later, but for now just be aware of the shortcut:\n(Windows) C + /\n(Mac) cmd + / \n-> Write a couple of random lines below this block comment, grab them and try the shortcut!\n'

## Ch 2 : Data Types + Basic Operation


Look [here](https://en.wikibooks.org/wiki/Python_Programming/Data_Types) for details. I will not explain every one of these.

Pay particular attention to [list](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists), [tuple](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences) and [dict](https://docs.python.org/3/tutorial/datastructures.html#dictionaries). These will come in handy as you go forward.

But, if I were to make a comparison with Java data types...
* list : array / stack / queue / arraylist....
* tuple : technically, does not exist in Java
* dict : Hashmap

Don't worry if you don't know what the Hashmap and queues and such are. Its behavior / format should be clear soon.

### A. List + Loop
Recall that, up to CS170 and even CS171, you've learned For-Loop and While-Loop and specifically used it to look at elements within an array. Exactly the same here. How you iterate through the list, however, is slightly different. And if you've picked up [For-Each Loop](http://stackoverflow.com/questions/85190/how-does-the-java-for-each-loop-work), you are in good shape.

**While Loop**

In [3]:
# While Loop example:
i = a = 0      # i = 0, a = 0
while i < 5:
    a += i**2  # i ** 2 == i ^2
    i += 1     # i +=1 : i = i + 1
    
# What is value in a now?

In [4]:
a

30

Essentially, the while loop doesn't differ too much.
Just note the lack of parenthesis around the loop condition, as it is considered redundant.
However, this for loop is quite interesting so let's take a look.

**For Loop**

In [5]:
# For Loop example:
b = 0
for i in range(5):
    b += i**2
    
# What is value in a now?

In [6]:
b

30

Essentially, a for loop in python is equivalent to a For-Each Loop in Java. What is For-Each Loop, you ask?

In java, you learned in the very beginning that, in order to iterate an array of length 5:

```java
int[] a = {1, 2, 3, 4, 5},
for(int i = 0; i < a.length; i++){
    System.out.println(a[i]);
}
```

But, this accomplishes exactly the same task:

```java
int[] b = a;
for(int c : b){
    System.out.println(c);
}
```

Basically, the below version says:
> Hey, I know that the array variable b only conatins elements of type int.
> So, starting from index 0, just give me that element without me having to explicity specify the location of each element

also check out [enumerate](https://docs.python.org/3/library/functions.html#enumerate)

In [7]:
t = ['Single Quote String element', "Double Quote String", 123, -0.49]
for i, value in enumerate(t):
    print(i)
    print(value)
    print(t[i])
    print()
#     if i > 1:
#         break

0
Single Quote String element
Single Quote String element

1
Double Quote String
Double Quote String

2
123
123

3
-0.49
-0.49



#### You CAN change the value of the array elements in the first method. But you CANNOT change the value of the array elements in the second method!!!!
## -> Why??

#### [Range](https://docs.python.org/3/library/functions.html#func-range)

In [8]:
# Let's test this in python. First, let me show what range() function gives us.
print(range(5))

range(0, 5)


In [9]:
# That wasn't too helpful. Let me try the for-loop instead:
for i in range(5):
    # only argument ::: stop (excluding)
    print (i)

0
1
2
3
4


In [10]:
# Perhaps you can now visualize what the range(5) looks like? Let me try with a different set of arguments:
for j in range(1, 6):
    # first argument  ::: start (including)
    # second argument ::: stop (excluding)
    print(j)

1
2
3
4
5


In [11]:
for abc in range(1, 10, 3):
    # first argument  ::: start (including)
    # second argument ::: stop (excluding)
    # third argument  ::: step
    print(abc)

1
4
7


To summmarize,
```python
range(5) ::: [0, 1, 2, 3, 4]
range(1, 4) ::: [1, 2, 3]
range(1, 10, 4) ::: [1, 5, 9]
```
Given this range, the for loop assigns a temporary variable that you give in the 
```python
for my_var in range(5):
```
to stand for each value of the list.

Oh and note that, unlike in Java, the convention for naming in python doesn't seem to be camelcase. Rather, use underscore.

** List**

In [12]:
# Let's work directly with custom lists.
a_list = [1, 2, 3] # equivalent to an int array in Java
b_list = [-5.0, "this is a string", 9] # ?????? doesn't care about data type of constituent elements

In [13]:
# how many elements?
print( len(a_list) )
print( len(b_list) )

3
3


In [14]:
# append new data
a_list.append(4)
print(a_list)

[1, 2, 3, 4]


In [15]:
# remove a second-index data
del a_list[1]
print(a_list)

[1, 3, 4]


In [16]:
# pop randomly
p1 = b_list.pop()
print(p1, b_list)

9 [-5.0, 'this is a string']


In [17]:
# pop from root
p2 = b_list.pop(0)
print(p2, b_list)

-5.0 ['this is a string']


In [18]:
# is an element in the list?
print(a_list)
print(3 in a_list)
print(2 in a_list)

[1, 3, 4]
True
False


In [19]:
# exactly where???
print(a_list)
print(a_list.index(3))
print(a_list.index(2 )) # error

[1, 3, 4]
1


ValueError: 2 is not in list

### Slicing
**IMPORTANT!!!!** Read [this](http://stackoverflow.com/questions/509211/explain-pythons-slice-notation). And remind yourself of the how the arguments worked for the range() function above. I will assume that you've read the link here.

In [20]:
# new toy lists:
c_list = [3.0, 92, "this is not the end", "amazon", "09"]
d_list = ["12.0f", -90]
e_list = [c_list, d_list, (c_list, d_list)]

In [21]:
# Quick Question:
# print( len(e_list) )

In [22]:
# last element, c_list
print(c_list[-1])

# second last element, d_list
print(d_list[-2])

09
12.0f


In [23]:
# odd index elements, c_list
print( c_list[::2])

[3.0, 'this is not the end', '09']


##### Might not be obvious why this is so important, but you will know soon enough.

In [24]:
# Now focus on e_list....
for e in e_list:
    print(type(e), e)
    print() # new line

<class 'list'> [3.0, 92, 'this is not the end', 'amazon', '09']

<class 'list'> ['12.0f', -90]

<class 'tuple'> ([3.0, 92, 'this is not the end', 'amazon', '09'], ['12.0f', -90])



In [25]:
for e in e_list:
    for ee in e: # nested lists!!!
        print(type(ee), ee)
    print() # new line

<class 'float'> 3.0
<class 'int'> 92
<class 'str'> this is not the end
<class 'str'> amazon
<class 'str'> 09

<class 'str'> 12.0f
<class 'int'> -90

<class 'list'> [3.0, 92, 'this is not the end', 'amazon', '09']
<class 'list'> ['12.0f', -90]



##### So:
Lists are an intuitive way to store data in your computation. What's even cooler?

# List Comprehension !!!!!

want : [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, ... 100]
how to define this??

In [26]:
res = list(range(2, 102, 2))
print(res)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


want : [1, 2, 5, 10, 17, 26, 37, ..., 101]
how to define this??

In [27]:
res = [i**2 + 1 for i in range(11)] # pythonic list comprehension
print(res)

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82, 101]


for each output of the inner for loop, we are essentially storing it into the larger list which embraces the entire expression
```python
i**2 + 1 for i in range(11)
```

In [28]:
# same as above
res = list(i**2 + 1 for i in range(11)) # often seen in python 2
print(res)

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82, 101]


In [29]:
# List comprehension can also if conditions!
res = [i**2 + 1 for i in range(1, 11) if (i)%2 == 0] # only even indices
print(res)

[5, 17, 37, 65, 101]


In [30]:
# random additional feature :)
a = [1, 2, 3, 4]
print(a)

b = [c + c**3 for c in a]
print( a + b)

[1, 2, 3, 4]
[1, 2, 3, 4, 2, 10, 30, 68]


**Question** : How to form an array that computes the sum of each index of a and b and places it into a new array in one line?? 

** Some computations**

In [31]:
# Toy lists
a = [1, 2, 3, 4]
b = [c + c**3 for c in a]
c = [i **2 for i in a]
print(a)
print(b)
print(c)

[1, 2, 3, 4]
[2, 10, 30, 68]
[1, 4, 9, 16]


In [32]:
# max, min
print( max(a), max(b) )
print( min(a), min(b) )

4 68
1 2


In [33]:
# Element-wise addition
print( [i + j for i, j in zip(a, c)] )

[2, 6, 12, 20]


##### In reality, math-intensive computations are done with external libraries. Check out [numpy](http://www.numpy.org/)

In [34]:
import numpy as np

In [35]:
a = np.array(a)
b = np.array(b)
c = np.array(c)
print(a)
print(b)
print(c)

[1 2 3 4]
[ 2 10 30 68]
[ 1  4  9 16]


In [36]:
# mean
print (np.average(b) )

27.5


In [37]:
# Element-wise Sum / Substraction
print(a + b)
print(c - b)

[ 3 12 33 72]
[ -1  -6 -21 -52]


In [38]:
# Element-wise Multiplication / Division
print(a**4)
print(b / 2)

[  1  16  81 256]
[  1.   5.  15.  34.]


##### numpy heavily used in any scientific programming environment, which includes machine learning.

[Tensorflow](https://www.tensorflow.org/) example

```python
# Snippet 3
# Softmax and cross entropy.

# Note that tf.nn.softmax REQUIRES the input to be of rank 2, and the logits
# below has a batch_size of 1 for illustration purpose.
logits = np.array([[0.95, 0.95]])
# The probability representation of the labels has the same shape as logits.
# Unlike logits, it is usually a batch of sparse vectors, where each vector
# has 1 on the correct position and 0 on the others.
labels = np.array([[1.0, 0.0]])
# Sometimes we chose to represent each label as its label index (an integer)
# instead of a probability. In our case the first (and the only) label has 
# 1.0 on index 0, so the sparse label representation will be "0".
sparse_labels = np.array([0], dtype=np.int32)

# Calculate the expected softmax and cross entropy.
#
# According to the definition of softmax, applying the softmax on it will 
# yield [[0.5, 0.5]]
expected_softmax = np.array([[0.5, 0.5]])
# Calcuate the cross entropy based on its definition. For details, see
# https://en.wikipedia.org/wiki/Cross_entropy
expected_cross_entropy = np.array([- 1.0 * np.log(0.5) - 0.0 * np.log(0.5)])

# Operation that produces the cross entropy from logits and labels.
cross_entropy_a = tf.nn.softmax_cross_entropy_with_logits(logits, labels)
# Operation that produces the cross entropy from logits and labels.
cross_entropy_b = tf.nn.sparse_softmax_cross_entropy_with_logits(logits, sparse_labels)

with tf.Session() as sess:
    # They should evaluate to the same vector (tensor).
    print(expected_cross_entropy)
    print(sess.run(cross_entropy_a))
    print(sess.run(cross_entropy_b))
```
[reference](https://github.com/breakds/tensorflow-snippets/blob/master/snippets/softmax_and_cross_entropy.ipynb)

**Dictionary**

If a list is an ordered sequence of values indexed by integer starting from 0, 1, 2, 3..
**Dictionary** provides an additional way to pair the value with other data types. This is pretty vague, so let's see...

In [39]:
from random import randint

In [40]:
# list of random integers from 0 to 9
rand = [randint(0, 9) for _ in range(5)]
print(rand)

[1, 4, 9, 6, 2]


If all you need is a container to store them in the way that they appear, lists are just fine.

**However**, let's imagine that we are playing a poker game. Player A must receive two cards of random digits from 1(ace) through 13(king), and same for Player B, C, D, etc...

You could assign an integer 0 to A, 1 to B, 2 to C, etc and come up with this:

In [41]:
# using list
num_player = 4
poker_init = [(randint(1, 13),randint(1, 13)) for _ in range(num_player) ]
for hand in poker_init:
    if i == 0:
        player = "A"
    elif i == 1:
        player = "B"
    elif i == 2:
        player = "C"
    else:
        player = "D"
    print("Player {} has the cards {}.".format(player, hand))

Player D has the cards (2, 10).
Player D has the cards (8, 2).
Player D has the cards (5, 3).
Player D has the cards (5, 5).


If **You** remember that index of 0 refers to player A's hands, but it's only you who knows this. When programming, must think about how to present our data in a understandable format to the users. 

-> UI/UX (User Interface / User Experience)

In [42]:
# using dict
num_player = 4

# these two lines might be confusing, but don't worry at this point.
# just look at what has been stored in the poker variable!
begin_char = ord("A")
poker = {chr(begin_char + i): (randint(1, 13), randint(1, 13)) for i in range(num_player)}
print (poker)

{'A': (13, 5), 'B': (10, 11), 'C': (8, 10), 'D': (8, 6)}


In [43]:
# Want to know what A has at this point?
print(poker['A'])

(13, 5)


So...
* List -> key: integer ::: value: any
* Dict -> key: any ::: value: any

#### Iteration

In [44]:
# (1) key only
for i in poker:
    print(i)

A
B
C
D


In [45]:
# (2) value only
for v in poker.values():
    print(v)

(13, 5)
(10, 11)
(8, 10)
(8, 6)


In [46]:
# (3) key and value
for k, v in poker.items():
    print(k)
    print(v)
    print()

A
(13, 5)

B
(10, 11)

C
(8, 10)

D
(8, 6)



**Efficiency: O(1) get and put. **
However, keys and values are stored unordered!

> When to use what depends on what you want to do.

**Tuple**

In [47]:
# immutable, ordered
a_tup = (4, 5)
print(a_tup)

(4, 5)


In [48]:
# can iterate through it
for i in a_tup:
    print(i)

4
5


In [49]:
# Usually used when a function returns more than one value.
# Functions will be covered a bit later.

In [50]:
# Just note, tuples can be used as keys to dicts
# let's say, Player E joins in the middle of the game to help player D out.
print(poker)
poker[('D', 'E')] = poker['D']
del poker['D']
print(poker)

{'A': (13, 5), 'B': (10, 11), 'C': (8, 10), 'D': (8, 6)}
{'A': (13, 5), 'B': (10, 11), 'C': (8, 10), ('D', 'E'): (8, 6)}


In [51]:
poker[('D', "E")]

(8, 6)